apiVersion: v2
appVersion: 0.12.7
description: Remote development environments on your infrastructure
home: https://github.com/coder/coder
icon: https://helm.coder.com/coder_logo_black.png
keywords:
- coder
- terraform
kubeVersion: '>= 1.19.0-0'
maintainers:
- email: support@coder.com
  name: Coder Technologies, Inc.
  url: https://coder.com/contact
name: coder
sources:
- https://github.com/coder/coder/tree/main/helm
type: application
version: 0.12.7
